kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics
  namespace: test
  labels:
    app: metrics
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: metrics
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metrics
        deployment: metrics
    spec:
      containers:
        - name: metrics
          image: 'image-registry.openshift-image-registry.svc:5000/test/metrics:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sleep
  namespace: test
  labels:
    app: sleep
    app.kubernetes.io/component: sleep
    app.kubernetes.io/instance: sleep
    app.kubernetes.io/name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sleep
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleep
        deployment: sleep
    spec:
      containers:
        - name: sleep
          image: 'image-registry.openshift-image-registry.svc:5000/test/sleep:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600