apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  namespace: test
spec:
  endpoints:
    - interval: 1s
      port: web
      scheme: http
  selector:
    matchLabels:
      app: metrics